# Generated by Django 3.1 on 2020-08-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
