# Generated by Django 3.1 on 2020-08-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200820_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stripe_payment_intent',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
