# Generated by Django 3.1 on 2020-08-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
