# Generated by Django 3.1 on 2020-08-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200820_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='banned_dates',
            field=models.ManyToManyField(blank=True, to='reservations.BannedDate'),
        ),
    ]
